/** 비로그인 공격대 탭 미리보기용 정적 데이터 */

export const DEMO_MY_GROUPS = [
  {
    id: 'demo',
    name: '원정대',
    description: '에기르 EX·세르카 나메 정기 공대. 멤버 숙제 현황 공유 모임.',
    isPublic: true,
    maxMembers: 16,
    memberCount: 7,
    myRole: 'leader',
    pendingCount: 2,
    leader: { name: '봄봄장' },
  },
  {
    id: 'demo-my-2',
    name: '숙제 같이해요',
    description: '길드원끼리 주간 레이드 숙제 현황 공유.',
    isPublic: false,
    maxMembers: 12,
    memberCount: 9,
    myRole: 'member',
    pendingCount: 0,
    leader: { name: '숙제장' },
  },
  {
    id: 'demo-my-3',
    name: '주말 레이드반',
    description: '토·일 오후 카제로스 런. 숙제 체크 후 일정 조율.',
    isPublic: true,
    maxMembers: 20,
    memberCount: 11,
    myRole: 'member',
    pendingCount: 0,
    leader: { name: '주말장' },
  },
]

export const DEMO_PUBLIC_GROUPS = [
  {
    id: 'demo-pub-1',
    name: '친구랑 숙제하기',
    description: '1730+ 친목 위주 레이드 숙제 공유 모임. 초보 환영.',
    isPublic: true,
    maxMembers: 20,
    memberCount: 14,
    leader: { name: '친목장' },
    hasPending: false,
    createdAt: new Date('2025-03-01'),
  },
  {
    id: 'demo-pub-2',
    name: '수요일 숙제단',
    description: '매주 수요일 초기화 때 레이드 현황 같이 체크해요.',
    isPublic: true,
    maxMembers: 16,
    memberCount: 13,
    leader: { name: '수요단장' },
    hasPending: true,
    createdAt: new Date('2025-02-15'),
  },
  {
    id: 'demo-pub-3',
    name: '가볍게 레이드해요',
    description: '부담 없이 레이드 숙제 같이 관리하는 소모임.',
    isPublic: true,
    maxMembers: 24,
    memberCount: 18,
    leader: { name: '가벼운장' },
    hasPending: false,
    createdAt: new Date('2025-04-10'),
  },
  {
    id: 'demo-pub-4',
    name: '숙제 인증 모임',
    description: '주간 레이드 완료 후 인증하는 소규모 모임.',
    isPublic: true,
    maxMembers: 10,
    memberCount: 6,
    leader: { name: '인증장' },
    hasPending: false,
    createdAt: new Date('2025-05-01'),
  },
]
