/** 비로그인 그룹 탭 미리보기용 정적 데이터 */

export const DEMO_MY_GROUPS = [
  {
    id: 'demo',
    name: '카제로스 원정단',
    description: '서카 ~ 아르모차 정기 공대. 멤버 숙제 공유 UI 예시입니다.',
    isPublic: true,
    maxMembers: 24,
    memberCount: 8,
    myRole: 'leader',
    pendingCount: 2,
    leader: { name: '샘플리더' },
  },
  {
    id: 'demo-my-2',
    name: '에기르 EX 도전단',
    description: '에기르 나이트메어 주 2회.',
    isPublic: false,
    maxMembers: 16,
    memberCount: 12,
    myRole: 'member',
    pendingCount: 0,
    leader: { name: '샘플부관' },
  },
  {
    id: 'demo-my-3',
    name: '아르모차 주말반',
    description: '토·일 오후 런.',
    isPublic: true,
    maxMembers: 20,
    memberCount: 10,
    myRole: 'member',
    pendingCount: 0,
    leader: { name: '주말장' },
  },
]

export const DEMO_PUBLIC_GROUPS = [
  {
    id: 'demo-pub-1',
    name: '루페온 레이드 공대',
    description: '1730 이상 환영. 초보 친화.',
    isPublic: true,
    maxMembers: 30,
    memberCount: 22,
    leader: { name: '루페온샘플' },
    hasPending: false,
    createdAt: new Date('2025-03-01'),
  },
  {
    id: 'demo-pub-2',
    name: '카제로스 하드 클리어단',
    description: '종막 카제 하드 공략.',
    isPublic: true,
    maxMembers: 16,
    memberCount: 15,
    leader: { name: '카제샘플' },
    hasPending: true,
    createdAt: new Date('2025-02-15'),
  },
  {
    id: 'demo-pub-3',
    name: '서카라베 나이트메어반',
    description: '서카 나메 정기.',
    isPublic: true,
    maxMembers: 20,
    memberCount: 18,
    leader: { name: '서카샘플' },
    hasPending: false,
    createdAt: new Date('2025-04-10'),
  },
  {
    id: 'demo-pub-4',
    name: '모르둠 노말 입문반',
    description: '모르둠 노말 첫 도전.',
    isPublic: true,
    maxMembers: 30,
    memberCount: 8,
    leader: { name: '입문샘플' },
    hasPending: false,
    createdAt: new Date('2025-05-01'),
  },
]
